default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: ad
  password: ad
  port: 5432

development:
  <<: *default
  database: kestone_dev

test:
  <<: *default
  username: postgres
  host: postgres
  password: ''
  database: kestone_test