default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: jgraft
  password: my1daddy
  port: 5432

development:
  <<: *default
  database: kestone_dev

test:
  <<: *default
  database: kestone_test